# This workflow will build a Java project with Maven 
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

#ワークフロー名を「Java CI with Maven」に設定
name: Build and Push

#masterブランチへのpush時にこのワークフローを実行するよう指定
on:
  push:
    branches: [ main ]

#以下JOB
jobs:
  #ジョブ名(build)を設定
  build-and-push:
    #ジョブの実行環境
    runs-on: ubuntu-latest

    #実行する処理やコマンドを指定
    steps:
    - uses: actions/checkout@v2 #リポジトリからのチェックアウトを行う「actions/checkout」アクションを実行する

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.6'

    - name: Maven purge
      run: ./mvnw dependency:purge-local-repository -DreResolve=false -f springtaskapp-parent/pom.xml

    - name: Build and Test with Maven
      run: ./mvnw clean package -f springtaskapp-parent/pom.xml

    #
    #ここからDocker
    #
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build, tag, and push image to Github
      env:
        DOCKERHUB_REPOSITORY: springtaskapp
        IMAGE_TAG: github3
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPOSITORY:$IMAGE_TAG springtaskapp-spring
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKERHUB_REPOSITORY:$IMAGE_TAG
